#pragma once
/*
#define WIFI_SSID "REPLACE_WITH_YOUR_SSID"
#define WIFI_PASSWORD "REPLACE_WITH_YOUR_PASSWORD"
*/


//DEBUG CONFIG
#define ENABLE_SERVER_COMMUNICATION 1 // 0: Desactivar, 1: Activar
#define FORCE_RTC_ADJUST 0 // 0: No ajustar, 1: Ajustar con fecha de compilacion
#define DEBUG_TEMPERATURE_LOGGER 0
//EN SystemController::cargarConfiguracion descomentar una vez para el guardado del nuevo umbral
#define DEBUG_EEPROM 0
#define DEBUG_RFID 1
#define DEBUG_SMS 0

#define WIFI_SSID "Moran"
#define WIFI_PASSWORD "02830193"

#define SERVER_BASE_URL "https://tempsegura.orbitar.dev/api"
#define ACTIVATION_KEYWORD "e7d106732a19df38"

#define FIRMWARE_VERSION "1.0.0"
#define PROTOCOL_VERSION "2.0"

// En uso normal debe quedar en 0. Solo poner 1 si queres forzar /esp/register.
#define FORCE_REGISTER 0

// Si el backend no devuelve shared_secret en /esp/register, dejar cargado el
// secreto provisionado para la MAC del ESP. Si ya quedo guardado en Preferences,
// puede quedar vacio.
#define MANUAL_SHARED_SECRET "b45f063b9605742450c78649b78e18aca47e9b4fc23571e60e046fa3853f0462"

// Prueba: 1 = HTTPS sin validar CA.
// Produccion: 0 = HTTPS validando la cadena de certificados.
#define USE_INSECURE_TLS_FOR_TEST 0

// Epoch aproximado por si NTP falla antes de validar TLS.
#define TLS_FALLBACK_EPOCH 1782699725UL

// Pegar la cadena PEM completa que te funciono: certificado del sitio +
// intermedios/raices, cada bloque con BEGIN/END CERTIFICATE.
#define TEMPSEGURA_ROOT_CA_PEM R"EOF(
    -----BEGIN CERTIFICATE-----
    MIIDtTCCAzygAwIBAgISBjloucZPAdkwZXudPLSOXRWJMAoGCCqGSM49BAMDMDMx
    CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQDEwNZ
    RTEwHhcNMjYwNjA4MTg0NTUwWhcNMjYwOTA2MTg0NTQ5WjAhMR8wHQYDVQQDExZ0
    ZW1wc2VndXJhLm9yYml0YXIuZGV2MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE
    e27Y8r7GA4yWahl0sruyevEo2spvRjYch2A6/2vMhwW+gKZ+QW7V6BviQcEnNsUW
    RsVrRooXbQG8eC0qhNgTGKOCAkAwggI8MA4GA1UdDwEB/wQEAwIHgDATBgNVHSUE
    DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBSZdh3Egr5u3Csp
    zFxEKaVk1GbTQTAfBgNVHSMEGDAWgBS7IMpHC/7X5Zz5jwkqo4w3RbG82DAzBggr
    BgEFBQcBAQQnMCUwIwYIKwYBBQUHMAKGF2h0dHA6Ly95ZTEuaS5sZW5jci5vcmcv
    MD0GA1UdEQQ2MDSCFnRlbXBzZWd1cmEub3JiaXRhci5kZXaCGnd3dy50ZW1wc2Vn
    dXJhLm9yYml0YXIuZGV2MBMGA1UdIAQMMAowCAYGZ4EMAQIBMC4GA1UdHwQnMCUw
    I6AhoB+GHWh0dHA6Ly95ZTEuYy5sZW5jci5vcmcvMTAuY3JsMIIBDAYKKwYBBAHW
    eQIEAgSB/QSB+gD4AHYA1219ENGn9XfCx+lf1wC/+YLJM1pl4dCzAXMXwMjFaXcA
    AAGeqMO7SAAABAMARzBFAiEAsdUEAik2wFb8fSbE15KbRd0KQDhVyGtxupnX/E2M
    s20CIH/41ZpGBzxH82e5eg1kij0wtvvEc7InYw7ZuOfypr8DAH4AbP5QGUOoXqkW
    vFLRM+TcyR7xQRx9JYQg0XOAnhgY6zoAAAGeqMO+0gAIAAAFAA94qbIEAwBHMEUC
    IQDA5ujOUZ5W8qcnTBY392ZUrEJ7FdTWnGzEDATfNHNy2wIgNGUzcNXVrOXek5xd
    TqGog0+B9oGS1LgD1HKs0+W+4eEwCgYIKoZIzj0EAwMDZwAwZAIwRea6zId2njIl
    z7TqB9oipjsuJgrCubPJ+JTyH8PxG+elvwvetCY6H6IyxtVA6SEjAjA3YzyliQmQ
    85PU90Qh66hJroa2INQjh6qrt+rxeC60kMWnrFa6yurBBepw2g+Zv1o=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICizCCAhGgAwIBAgIQXd1w3TH4AchcGGp6BLgK/jAKBggqhkjOPQQDAzAuMQsw
    CQYDVQQGEwJVUzENMAsGA1UEChMESVNSRzEQMA4GA1UEAxMHUm9vdCBZRTAeFw0y
    NTA5MDMwMDAwMDBaFw0yODA5MDIyMzU5NTlaMDMxCzAJBgNVBAYTAlVTMRYwFAYD
    VQQKEw1MZXQncyBFbmNyeXB0MQwwCgYDVQQDEwNZRTEwdjAQBgcqhkjOPQIBBgUr
    gQQAIgNiAAQHZVB1/mimla2hfSurylScjPMZaOJXLz/NnAc2sylm8WDyhU9Ccp+z
    ASQi5vSwGGJjSGklkD9fdPR8GpyDIOIjCEfrnbt/v+ZSEPLLEGbaM6EccDbN7p9x
    teIm2Avf+ryjge4wgeswDgYDVR0PAQH/BAQDAgGGMBMGA1UdJQQMMAoGCCsGAQUF
    BwMBMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYDVR0OBBYEFLsgykcL/tflnPmPCSqj
    jDdFsbzYMB8GA1UdIwQYMBaAFKPIJlqOoUzQNWP8myPIOq5W809WMDIGCCsGAQUF
    BwEBBCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL3llLmkubGVuY3Iub3JnLzATBgNV
    HSAEDDAKMAgGBmeBDAECATAnBgNVHR8EIDAeMBygGqAYhhZodHRwOi8veWUuYy5s
    ZW5jci5vcmcvMAoGCCqGSM49BAMDA2gAMGUCMQDgjUEahFT/h3DRakqiPZpLvPgf
    Zwkt6K2EOMmh1nvEzl83eMLYcod4GCl3b0J1Nn0CMBNYmEQJb4CEG5WoOe7aRn/L
    VKu6saHmHEynI7ysIPd8zQsK1HdmhlHKlw9Z5GpGvA==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICpjCCAiugAwIBAgIRAIchZfw0tuX7qK3Vs3BftTowCgYIKoZIzj0EAwMwTzEL
    MAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2VhcmNo
    IEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDIwHhcNMjYwNTEzMDAwMDAwWhcN
    MzIwOTAyMjM1OTU5WjAuMQswCQYDVQQGEwJVUzENMAsGA1UEChMESVNSRzEQMA4G
    A1UEAxMHUm9vdCBZRTB2MBAGByqGSM49AgEGBSuBBAAiA2IABDwS/6vhrcVqcbBo
    +wgdI3fwn9x7DNJJOY/lTOti0vkwuRN87RhEhTH17E7XyFjWsPYhIPt/wzOqxTd2
    b+4ZJNy9ID04YywF9U5zasDVyGSNErVNtz8uSGh5izW87j77GaOB6zCB6DAOBgNV
    HQ8BAf8EBAMCAQYwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUo8gmWo6hTNA1Y/ybI8g6rlbzT1YwHwYDVR0jBBgwFoAUfEKW
    rt5LSDv6kviejM9ti6lyN5UwMgYIKwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZo
    dHRwOi8veDIuaS5sZW5jci5vcmcvMBMGA1UdIAQMMAowCAYGZ4EMAQIBMCcGA1Ud
    HwQgMB4wHKAaoBiGFmh0dHA6Ly94Mi5jLmxlbmNyLm9yZy8wCgYIKoZIzj0EAwMD
    aQAwZgIxAMU19WCtmxVND8UHBZRoma49Z7jPs64Dma0eTu1OChVbB/2J7GV3nvYK
    Ax54uk1G9QIxAO0miLVJu8PLNiXXXkiE/gsK3CTRTF/aeo4bMX42Zw40csRU6AC2
    6hSW1/IWaas6dg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICGzCCAaGgAwIBAgIQQdKd0XLq7qeAwSxs6S+HUjAKBggqhkjOPQQDAzBPMQsw
    CQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJuZXQgU2VjdXJpdHkgUmVzZWFyY2gg
    R3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBYMjAeFw0yMDA5MDQwMDAwMDBaFw00
    MDA5MTcxNjAwMDBaME8xCzAJBgNVBAYTAlVTMSkwJwYDVQQKEyBJbnRlcm5ldCBT
    ZWN1cml0eSBSZXNlYXJjaCBHcm91cDEVMBMGA1UEAxMMSVNSRyBSb290IFgyMHYw
    EAYHKoZIzj0CAQYFK4EEACIDYgAEzZvVn4CDCuwJSvMWSj5cz3es3mcFDR0HttwW
    +1qLFNvicWDEukWVEYmO6gbf9yoWHKS5xcUy4APgHoIYOIvXRdgKam7mAHf7AlF9
    ItgKbppbd9/w+kHsOdx1ymgHDB/qo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0T
    AQH/BAUwAwEB/zAdBgNVHQ4EFgQUfEKWrt5LSDv6kviejM9ti6lyN5UwCgYIKoZI
    zj0EAwMDaAAwZQIwe3lORlCEwkSHRhtFcP9Ymd70/aTSVaYgLXTWNLxBo1BfASdW
    tL4ndQavEi51mI38AjEAi/V3bNTIZargCyzuFJ0nN6T5U6VR5CmD1/iQMVtCnwr1
    /q4AaOeMSQ+2b1tbFfLn
    -----END CERTIFICATE-----
)EOF"

#define USER_ID "99999"
#define USER_PASS "12345"

#define PHONE_NUMBER "+542613638639"

// Ajustar pines segun tu placa ESP32.
#define ONE_WIRE_BUS 26

#define BUZZER_PIN 25
#define LED_ROJO_PIN 25

#define DISPLAY_CLK 22
#define DISPLAY_DIO 21

#define SIM800_RX 17
#define SIM800_TX 16

#define RFID_SS1_CARGA 5
#define RFID_SS2_DESCARGA 4
#define RFID1_RST 14
#define RFID2_RST 27

#define RTC_SDA 32
#define RTC_SCL 33

#define TEMP_SENTINEL 128.8f
#define MAX_SAMPLES 6

#define DEFAULT_UMBRAL_SUP 8
#define DEFAULT_UMBRAL_INF 2

#define EEPROM_SIZE 4096
#define STORAGE_MAX_RECORDS 24
